project:
  type: website
  output-dir: gh-pages

website:
  title: "Latent Space Notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/latentspacenotes
      - icon: twitter
        href: https://twitter.com/latentspacepod
format:
  html:
    theme: cosmo
    css: styles.css



