project:
  type: website
  output-dir: gh-pages

website:
  title: "Latent Space Notes"
  navbar:
    right:
      - icon: github
        href: https://github.com/latentspacenotes
      - icon: twitter
        href: https://twitter.com/latentspacepod
  site-url: https://latentspacenotes.github.io
  twitter-card: true
  open-graph: true
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css